apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}-depl"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ConfigMap.yaml") . | sha256sum }}
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
        - name: "{{ .Values.name }}"
          image: "{{ .Values.deployment.repository }}/{{ .Values.name }}:{{ .Values.deployment.tag }}"
          imagePullPolicy: Always
          {{- if .Values.deployment.resources }}
          resources:
            {{- if .Values.deployment.resources.requests }}
            requests:
              memory: {{ .Values.deployment.resources.requests.memory | default "250Mi" | quote }}
              cpu: {{ .Values.deployment.resources.requests.cpu | default "30m" | quote }}
            {{- else}}
            requests:
              memory: "250Mi"
              cpu: "30m"
            {{- end}}
            {{- if .Values.deployment.resources.limits }}
            limits:
              memory: {{ .Values.deployment.resources.limits.memory | default "1024Mi" | quote }}
              cpu: {{ .Values.deployment.resources.limits.cpu | default "150m" | quote }}
            {{- else}}
            limits:
              memory: "1024Mi"
              cpu: "150m"
            {{- end }}
          {{- else }}
          resources:
            requests:
              memory: "250Mi"
              cpu: "30m"
            limits:
              memory: "1024Mi"
              cpu: "150m"
          {{- end }}
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Values.name }}-configmap"
                  key: database_url
